# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sandbox Position',
            },
        ),
    ]
