# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcopt_create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcoptExternalInputExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bw2_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Exchange (Input) from external technosphere',
            },
        ),
        migrations.CreateModel(
            name='LcoptExternalOutputExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bw2_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Exchange (Output) to external technosphere/biosphere',
            },
        ),
        migrations.CreateModel(
            name='LcoptIntermediateExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(choices=[('Mass', (('kg', 'kg'), ('t', 'tonne'))), ('Energy', (('kWh', 'kWh'),)), ('Volume', (('m3', 'm3'),)), ('Radioactivity', (('Bq', 'Bq'),)), ('Time', (('h', 'hours'), ('d', 'days'))), ('Amount', (('p', 'Item'),))], default='kg', max_length=5)),
                ('code', models.CharField(default=' ', max_length=36)),
                ('bw2_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Technosphere intermediate',
            },
        ),
        migrations.CreateModel(
            name='LcoptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='LcoptProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(choices=[('Mass', (('kg', 'kg'), ('t', 'tonne'))), ('Energy', (('kWh', 'kWh'),)), ('Volume', (('m3', 'm3'),)), ('Radioactivity', (('Bq', 'Bq'),)), ('Time', (('h', 'hours'), ('d', 'days'))), ('Amount', (('p', 'Item'),))], default='kg', max_length=5)),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('code', models.CharField(default=' ', max_length=36)),
                ('bw2_id', models.CharField(max_length=255)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcopt_create.LcoptModel')),
                ('input_exchanges', models.ManyToManyField(to='lcopt_create.LcoptExternalInputExchange')),
                ('output_exchanges', models.ManyToManyField(to='lcopt_create.LcoptExternalOutputExchange')),
                ('technosphere_exchanges_inputs', models.ManyToManyField(related_name='tech_exch_Inputs', to='lcopt_create.LcoptIntermediateExchange')),
                ('technosphere_exchanges_products', models.ManyToManyField(related_name='tech_exch_Products', to='lcopt_create.LcoptIntermediateExchange')),
            ],
            options={
                'verbose_name_plural': 'Transformation processes',
            },
        ),
    ]
